Repository Togedy/Togedy_Android, pull requests merged in 2024-12, with the labels that each got.

#13 [UI/#7] 커뮤니티 홈 & 글쓰기 화면 구현
  app/src/main/java/com/example/togedy_android/core/component/TogedyButtonBasic.kt
  app/src/main/java/com/example/togedy_android/core/component/TogedyPhotoInput.kt
  app/src/main/java/com/example/togedy_android/core/component/TogedyTextField.kt
  app/src/main/java/com/example/togedy_android/core/component/TogedyTitle.kt
  app/src/main/java/com/example/togedy_android/core/component/TogedyTopBar.kt
  app/src/main/java/com/example/togedy_android/domain/type/WritingType.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/bottom_nav/BottomNavigationBar.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/model/NavGraph.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/screens/community/AddWriting.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/screens/community/AddWritingViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/screens/community/CommunityScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/screens/community/component/CommunityFastTab.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/screens/community/component/CommunityHomeTobBar.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/screens/community/component/HomeBulletinBoard.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/screens/community/component/SelectingWritingType.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/screens/community/component/TrendingPostsSection.kt
  app/src/main/res/drawable/ic_alert_triangle.xml
  app/src/main/res/drawable/ic_annotation_dots_light_line.xml
  app/src/main/res/drawable/ic_building_light_line.xml
  app/src/main/res/drawable/ic_image_plus.xml
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/drawable/ic_shopping_bag_light_line.xml
  app/src/main/res/drawable/ic_trash_can.xml
  app/src/main/res/values/strings.xml
Labels: feat, 김채린

#17 [Feat/#8] GPT 화면 구현
  .idea/deploymentTargetSelector.xml
  .idea/kotlinc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/togedy_android/domain/type/MessageType.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/ChatData.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/ChatViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/GPTScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/component/MessageText.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/component/MessageTextField.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/navigation/GptNavigation.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/retrofit/ChatApiService.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/retrofit/RetrofitInstance.kt
  app/src/main/java/com/example/togedy_android/presentation/main/MainActivity.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/bottom_nav/BottomNavigationBar.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/bottom_nav/BottomNavigationItem.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/model/ChatViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/model/NavGraph.kt
  app/src/main/res/drawable/ic_right_arrow.xml
Labels: feat, 김태정

#19 [Chore/#18] Hilt dagger 네트워크 세팅 구축
  .gitignore
  app/build.gradle.kts
  app/src/main/java/com/example/togedy_android/TogedyApp.kt
  app/src/main/java/com/example/togedy_android/data/di/BaseResponse.kt
  app/src/main/java/com/example/togedy_android/data/di/NetWorkModule.kt
  app/src/main/java/com/example/togedy_android/data/di/RepositoryModule.kt
  app/src/main/java/com/example/togedy_android/data/di/XAccessTokenInterceptor.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todata/BoardWritingRequestMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/BoardListResponseMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/BoardWritingIdResponseMapper.kt
  app/src/main/java/com/example/togedy_android/data/model/response/LogInResponse.kt
  app/src/main/java/com/example/togedy_android/data/remote/LogInApi.kt
  app/src/main/java/com/example/togedy_android/data/remote/datasource/CommunityRemoteDataSource.kt
  app/src/main/java/com/example/togedy_android/data/remote/datasourceimpl/CommunityRemoteDataSourceImpl.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/base/BaseResponse.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/request/BoardWritingRequestDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/response/BoardListResponseDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/response/BoardWritingResponseDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/service/CommunityService.kt
  app/src/main/java/com/example/togedy_android/data/repositoryImpl/CommunityRepositoryImpl.kt
  app/src/main/java/com/example/togedy_android/data/repositoryImpl/LogInRepositoryImpl.kt
  app/src/main/java/com/example/togedy_android/data/util/BaseResponseHandler.kt
  app/src/main/java/com/example/togedy_android/di/DataSourceModule.kt
  app/src/main/java/com/example/togedy_android/di/NetworkModule.kt
  app/src/main/java/com/example/togedy_android/di/RepositoryModule.kt
  app/src/main/java/com/example/togedy_android/di/ServiceModule.kt
  app/src/main/java/com/example/togedy_android/di/qualifier/Qualifier.kt
  app/src/main/java/com/example/togedy_android/domain/model/BoardList.kt
  app/src/main/java/com/example/togedy_android/domain/model/BoardWriting.kt
  app/src/main/java/com/example/togedy_android/domain/model/BoardWritingId.kt
  app/src/main/java/com/example/togedy_android/domain/repository/CommunityRepository.kt
  app/src/main/java/com/example/togedy_android/domain/repository/LogInRepository.kt
  app/src/main/java/com/example/togedy_android/domain/usecase/login/GetLogInDataUseCase.kt
  app/src/main/java/com/example/togedy_android/presentation/community/CommunityForumScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/community/CommunityViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/community/component/CommunityForumListItem.kt
  app/src/main/java/com/example/togedy_android/presentation/community/component/ForumList.kt
  app/src/main/java/com/example/togedy_android/presentation/community/state/BoardListState.kt
  app/src/main/java/com/example/togedy_android/presentation/mypage/MyPageViewModel.kt
  app/src/main/res/drawable/ic_community_writing.xml
  app/src/main/res/drawable/img_example_board.png
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: chore, 김태정

#23 [Feat/#20] CommunityList, CommunityDetail UI 및 통신 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/togedy_android/data/local/SharedPreferenceManager.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/BoardDetailResponseMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/BoardListResponseMapper.kt
  app/src/main/java/com/example/togedy_android/data/remote/datasource/CommunityRemoteDataSource.kt
  app/src/main/java/com/example/togedy_android/data/remote/datasourceimpl/CommunityRemoteDataSourceImpl.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/base/BaseResponse.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/response/BoardDetailResponseDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/response/BoardListResponseDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/service/CommunityService.kt
  app/src/main/java/com/example/togedy_android/data/repositoryImpl/CommunityRepositoryImpl.kt
  app/src/main/java/com/example/togedy_android/data/util/BaseResponseHandler.kt
  app/src/main/java/com/example/togedy_android/di/NetworkModule.kt
  app/src/main/java/com/example/togedy_android/di/RepositoryModule.kt
  app/src/main/java/com/example/togedy_android/domain/model/BoardDetail.kt
  app/src/main/java/com/example/togedy_android/domain/model/BoardList.kt
  app/src/main/java/com/example/togedy_android/domain/repository/CommunityRepository.kt
  app/src/main/java/com/example/togedy_android/presentation/community/AddWriting.kt
  app/src/main/java/com/example/togedy_android/presentation/community/CommunityBoardScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/community/CommunityDetailScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/community/CommunityForumScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/community/CommunityScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/community/CommunityViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/community/component/CommunityForumListItem.kt
  app/src/main/java/com/example/togedy_android/presentation/community/navigation/CommunityNavigation.kt
  app/src/main/java/com/example/togedy_android/presentation/community/state/BoardDetailState.kt
  app/src/main/java/com/example/togedy_android/presentation/community/state/BoardListState.kt
  app/src/main/java/com/example/togedy_android/presentation/main/MainActivity.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/PlannerScreen.kt
  app/src/main/java/com/example/togedy_android/util/dateParsing.kt
  app/src/main/res/drawable/ic_community_reply.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_heart_clicked.xml
  app/src/main/res/drawable/ic_message.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feat, 김태정

#25 UI/#22 planner 기능 구현
  app/src/main/java/com/example/togedy_android/core/design_system/component/TogedyButtonBasic.kt
  app/src/main/java/com/example/togedy_android/core/design_system/component/TogedyTextField.kt
  app/src/main/java/com/example/togedy_android/core/design_system/component/TogedyTopBar.kt
  app/src/main/java/com/example/togedy_android/domain/entity/PlannerHomeInformation.kt
  app/src/main/java/com/example/togedy_android/domain/model/planner/DayOfPlan.kt
  app/src/main/java/com/example/togedy_android/domain/model/planner/PlanItem.kt
  app/src/main/java/com/example/togedy_android/domain/model/planner/StudyTag.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/CalendarScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/component/DayOfMonth.kt
  app/src/main/java/com/example/togedy_android/presentation/main/MainNavigator.kt
  app/src/main/java/com/example/togedy_android/presentation/main/MainScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/PlannerScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/component/PlannerDialogScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/component/PlannerInputSection.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/component/PlannerWeeklyCalendar.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/component/StudyTag.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/component/StudyTagDialog.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/component/TodaysGoal.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/navigation/PlannerNavigation.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/planner/PlannerRoute.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/planner/PlannerViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/planner/navigation/PlannerNavigation.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/planner/state/PlannerDialogState.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/planner/state/PlannerUiState.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/planner/type/PlannerDialogType.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/plannerCalendar/PlannerCalendarScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/plannerDetail/PlannerDetailScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/plannerDetail/PlannerDetailViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/plannerDetail/component/DailyPlanList.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/plannerDetail/component/TimeTable.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/plannerDetail/state/PlannerDetailIntent.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/plannerDetail/state/PlannerDetailUiState.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/setGoalTime/SetGoalTimeScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/setGoalTime/SetGoalTimeViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/state/PlannerUiState.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/stopwatch/StopWatchScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/bottom_nav/BottomNavigationBar.kt
  app/src/main/java/com/example/togedy_android/util/ColorFunction.kt
  app/src/main/res/drawable/ic_check_circle.xml
  app/src/main/res/drawable/ic_study_play.xml
  app/src/main/res/values/strings.xml
Labels: feat, 김채린

#27 [UI/#26] gpt redesign
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/GPTScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/component/InitialGPTScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/gptscreen/component/MessageText.kt
  app/src/main/res/drawable/ic_logo_face.png
Labels: feat, 김채린

#35 [Feat/#34] calendar detail 다이얼로그 구현
  app/src/main/java/com/example/togedy_android/core/design_system/component/TogedyTextField.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todata/DateRequestMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todata/calendar/CategoryItemMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todata/planner/DateRequestMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/calendar/CategoryIdMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/calendar/CategoryItemListMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/calendar/CategoryItemMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/calendar/DailyScheduleItemListMapper.kt
  app/src/main/java/com/example/togedy_android/data/mapper/todomain/calendar/MonthlyScheduleItemListMapper.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/calendar/request/CategoryItemRequestDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/calendar/response/CategoryIdResponseDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/calendar/response/CategoryItemResponseDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/calendar/response/DailyScheduleItemDto.kt
  app/src/main/java/com/example/togedy_android/data/remote/model/calendar/response/MonthlyScheduleItemDto.kt
  app/src/main/java/com/example/togedy_android/data/repositoryImpl/PlannerRepositoryImpl.kt
  app/src/main/java/com/example/togedy_android/domain/entity/PlannerHomeInformation.kt
  app/src/main/java/com/example/togedy_android/domain/model/DateModel.kt
  app/src/main/java/com/example/togedy_android/domain/model/calendar/CategoryId.kt
  app/src/main/java/com/example/togedy_android/domain/model/calendar/CategoryItem.kt
  app/src/main/java/com/example/togedy_android/domain/model/calendar/DailyScheduleItem.kt
  app/src/main/java/com/example/togedy_android/domain/model/calendar/MonthlyScheduleItem.kt
  app/src/main/java/com/example/togedy_android/domain/model/calendar/NewCategoryItem.kt
  app/src/main/java/com/example/togedy_android/domain/model/planner/Date.kt
  app/src/main/java/com/example/togedy_android/domain/model/planner/PlanItem.kt
  app/src/main/java/com/example/togedy_android/domain/model/planner/PlannerHomeInformation.kt
  app/src/main/java/com/example/togedy_android/domain/model/planner/StudyTagId.kt
  app/src/main/java/com/example/togedy_android/domain/repository/PlannerRepository.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/CalendarScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/addPersonalSchedule/AddPersonalScheduleScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/addPersonalSchedule/AddPersonalScheduleViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/calendar/CalendarRoute.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/calendar/CalendarViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/calendar/navigation/CalendarNavigation.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/calendar/state/CalendarDialogState.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/calendar/state/CalendarUiState.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/calendarDialog/CalendarDialogScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/calendarDialog/CalendarDialogViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/component/MonthlyCalendar.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/navigation/CalendarNavigation.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/univDetail/UnivDetailScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/univDetail/UnivDetailViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/univList/UnivListScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/calendar/univList/UnivListViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/main/MainNavigator.kt
  app/src/main/java/com/example/togedy_android/presentation/main/MainScreen.kt
  app/src/main/java/com/example/togedy_android/presentation/main/MainTab.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/planner/PlannerViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/planner/state/PlannerUiState.kt
  app/src/main/java/com/example/togedy_android/presentation/planner/plannerDetail/PlannerDetailViewModel.kt
  app/src/main/java/com/example/togedy_android/presentation/ui/bottom_nav/BottomNavigationBar.kt
  app/src/main/java/com/example/togedy_android/util/formatToSimpleDate.kt
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_search.xml
Labels: feat, 김채린
